### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by pradyumnasagar** [swsoyee/TCC-GUI#38]
Cannot start TCC-GUI

1. install all package as mentioned 
2. Run shiny::runApp("TCC-GUI-master//TCC-GUI", launch.browser = TRUE)

>  Listening on http://127.0.0.1:5541
> Warning in readLines(file, warn = FALSE) :
>   invalid input found on input connection 'server-simulation.R'
> Warning: Error in source: server-simulation.R:108:9: unexpected INCOMPLETE_STRING
> 107:         input$simulationGeneNum,
> 108:         " 
>              ^
>   50: source
>   49: server [/home/pradyumna/tools/Prady/TCCGUI/TCC-GUI/TCC-GUI/server.R#58]
> Error in source(file = "server-simulation.R", local = TRUE, encoding = "UTF-8") : 
>   server-simulation.R:108:9: unexpected INCOMPLETE_STRING
> 107:         input$simulationGeneNum,
> 108:         " 
> 
> 
![Screenshot from 2019-12-20 00-03-54](https://user-images.githubusercontent.com/10559871/71199587-4250a980-22bc-11ea-984f-41a77c18d860.png)

 - OS: Arch Linux
 - Browser chrome
 - R Version 3.6.2

**Comment by swsoyee** [comment]
@pradyumnasagar Thank you for considering to use TCC-GUI in your project!
The problem is quite simple, there is a `×` mark at line 108 in `server-simulation.R`, if your system doesn't include enough charset, it will cause the launching failed.

The mark is appear in 3 places in this project:
```
# Command
grep -n × *.R

# Result
server-simulation.R:108:        " × ",
server-simulation.R:110:        " × ",
server-tcc-calculation.R:196:                      " = Library Size × Normalization Factor."
```

I think just replace those mark and it will be work.
Since I don't have the same environment for reproducing this problem, it's very welcome to receive a pull request after you fix that.
