### ISSUE TITLE
Error in get_quosure

### ISSUE THREAD

**Issue by KenYoshi84** [swsoyee/TCC-GUI#50]
Using standalone version of TCC-GUI browser, after clicking "2. Assign Group Label", the browser is suddenly shut down and there appears the error message like following

警告:  Error in get_quosure:  関数 "get_quosure" を見つけることができませんでした 
  73: renderMenu
  72: observeEventHandler [server-tabPanel.R#6]
   1: runApp

Even if I used simulation data, the situation was the same.
However, using online version browser, I can proceed the analysis without any error.
I have followed the instruction of Method 1 as you described in the GitHub.
I also have installed all the packages required.
Do I need install other package?

**To Reproduce**
1. Open R Studio and open the ui.R, server.R or global.R in TCC-GUI directory, and click the Run App button to launch the application.
2. Click on 'Simulation data' and click on "Generate Simulation data" and create data successfully.
3. Click on "Exploratory analysis" and choose the simulation data followed by clicking "1. Import Count Data".
4. Scroll down to the group assignment and click the "2. Assign Group Label".
5. Error happen. The browser is shut down and the message described above appear in the Console.

I have no idea what is expected to happen.

Desktop
 - OS is Windows 10
 - Browser is chrome
 - Version 88.0.4324.150

Would you please give me some advices? Thank you.

**Comment by swsoyee** [comment]
@KenYoshi84 Thank you for your report. Maybe the reason is that you are using shiny 1.6 but the lockfile is outdated.
The new function `get_quosure()` has been added in `{shiny}` version 1.6 (https://github.com/rstudio/shiny/commit/9c915e52caf364b3e9841418e697e142a2f45bca) but the lockfile is still 1.5, so I update the lockfile.

You could pull the master code and use `renv::restore()` to load the all packages which are needed if you are using `{renv}` to have a check.

**Comment by KenYoshi84** [comment]
Actually, I was using shiny 1.5. However, maybe thanks to your update of lockfile, updating shiny from version1.5 to version 1.6 made it possible for me to complete an analysis without any error.
Thank you so much.

**Comment by swsoyee** [comment]
Thanks! Hope TCC-GUI could help you with your analysis!
